theme: jekyll-theme-cayman
title: BRIDGES 2027 Summer School in the South Pacific
description: "Bridging the Divides with Globally Engineered Software"
background: ""
repository: bridges-png/bridges-png.github.io
